// ALL UI MANIPULATION ACTION TYPES
export const UI_SIDEBAR_OPEN = "UI_SIDEBAR_OPEN"
export const UI_SIDEBAR_CLOSE = "UI_SIDEBAR_CLOSE"
export const UI_LOGIN_MODAL_OPEN = "UI_LOGIN_MODAL_OPEN"
export const UI_LOGIN_MODAL_CLOSE = "UI_LOGIN_MODAL_CLOSE"
export const UI_LOGOUT_MODAL_OPEN = "UI_LOGOUT_MODAL_OPEN"
export const UI_LOGOUT_MODAL_CLOSE = "UI_LOGOUT_MODAL_CLOSE"
export const UI_LOGIN_SET_ACT_TAB = "UI_LOGIN_SET_ACT_TAB"
export const UI_REACTO_MODAL_OPEN = "UI_REACTO_MODAL_OPEN"
export const UI_REACTO_MODAL_CLOSE = "UI_REACTO_MODAL_CLOSE"

export const USER_UPDATE = "USER_UPDATE"
export const USER_PREFS_UPDATE = "USER_PREFS_UPDATE"
export const USER_RESET = "USER_RESET"

export const ONLINE_DATA_SAVE_MY_TALES = "ONLINE_DATA_SAVE_MY_TALES"
export const ONLINE_DATA_CLEAR_TALES = "ONLINE_DATA_CLEAR_TALES"

export const TALE_CREATE = "TALE_CREATE"
export const TALE_SET_AS_WIP = "TALE_SET_AS_WIP"    // Set the given tale as WIP tale
export const TALE_UPDATE_INFO = "TALE_UPDATE_INFO"
export const TALE_STATE_CLEANUP = "TALE_STATE_CLEANUP"
export const TALE_UPDATE_REACTO_VARS = "TALE_UPDATE_REACTO_VARS"
export const TALE_PUBLISH = "TALE_PUBLISH"
export const TALE_UNPUBLISH = "TALE_UNPUBLISH"

// export const STORYLET_CREATE = "STORYLET_CREATE"
export const STORYLET_UPDATE_FIELD = "STORYLET_UPDATE_FIELD"
export const STORYLET_UPDATE_ALL_TEXT = "STORYLET_UPDATE_ALL_TEXT"
export const STORYLET_DELETE = "STORYLET_DELETE"

export const STORYBOARD_INIT = "STORYBOARD_INITIALIZE"
export const STORYBOARD_ADD_SINGLE = "STORYBOARD_ADD_SINGLE"
export const STORYBOARD_INSERT_AT = "STORYBOARD_INSERT_AT"
export const STORYBOARD_SELECT_CHOICE = "STORYBOARD_SELECT_CHOICE"

export const CHOICE_CREATE = "CHOICE_CREATE"
export const CHOICE_DELETE = "CHOICE_DELETE"
export const CHOICE_UPDATE_TEXT = "CHOICE_UPDATE_TEXT"
export const ADD_CID_TO_STID = "ADD_CID_TO_STID"

